[workspace]
members = ["derive", "lib"]
resolver = "2"

[workspace.package]
version = "0.1.1"
authors = [
  "Takumi Okamoto <takumi1988okamoto@gmail.com>",
  "Alexander Korolev <alexander.korolev.germany@gmail.com>",
]
edition = "2021"
homepage = "https://github.com/MrBearing/ros-cmake-parser"
license = "Unlicense OR MIT"
readme = "README.md"
repository = "https://github.com/MrBearing/ros-cmake-parser"

[workspace.dependencies]
ros-cmake-parser-derive = { version = "0.1.1", path = "derive" }
ros-cmake-parser = { version = "0.1.1", path = "lib" }
