[package]
name = "ros-cmake-parser"
categories = ["parser-implementations", "development-tools"]
description = """
Rust parser for CMake with raw command access and ROS-oriented helpers.
"""
keywords = ["cmake", "ros", "ament", "catkin", "parser"]

version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true

[dependencies]
thiserror = "1"
nom = "7"

ros-cmake-parser-derive = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.3.0"
inflections = "1.1.1"
check_keyword = "0.2"